### ISSUE TITLE
Importar Ct-e

### ISSUE THREAD

**Issue by RobsonSiegel** [gabrielbaltazar/GBFiscalReader#1]
seria possivel incluir a importação de CT-e?

[CTe41200903629957001161570010000561311728444505_procCTe.zip](https://github.com/gabrielbaltazar/GBFiscalReader/files/5336539/CTe41200903629957001161570010000561311728444505_procCTe.zip)

**Comment by gabrielbaltazar** [comment]
Implementado na versão 2.0.0
